### ISSUE TITLE
Create a first results of Hypothesis II

### ISSUE THREAD

**Issue by OndrejMottl** [HOPE-UIB-BIO/PastHumanImpact#82]
# Hypothesis II
- test if the interactions between ecosystem properties have been altered by historic humans

```[tasklist]
### Tasks
- [ ] https://github.com/HOPE-UIB-BIO/HOPE_Hypothesis1/issues/83
- [ ] #78
- [ ] https://github.com/HOPE-UIB-BIO/HOPE_Hypothesis1/issues/84
- [ ] https://github.com/HOPE-UIB-BIO/HOPE_Hypothesis1/issues/98
- [x] Create/update the visualisation of results to compare them with H1
```
