### ISSUE TITLE
Make a Word document on Teams

### ISSUE THREAD

**Issue by OndrejMottl** [HOPE-UIB-BIO/PastHumanImpact#93]
Teams allow working a document at the same time, so let's use it

```[tasklist]
### Tasks
- [x] Create Teams
- [x] Invite all leading authors
- [x] Make a new Word doc
- [ ] #113 
- [ ] Copy all current text to it
```
